name: Build

on: push

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: temurin
                  cache: maven

            - name: Debug JDK setup
              run: |
                  java -version
                  mvn -version
                  echo $JAVA_HOME

            - name: Launch tests
              run: mvn verify

            - uses: codecov/codecov-action@v4
              with:
                  fail_ci_if_error: true
                  token: ${{ secrets.CODECOV_TOKEN }}
                  verbose: true
